### PR TITLE
Added Screenshot and updated ReadMe.md

### PR DESCRIPTION
**Pull request by Neon-K9**
Hello,
Kamlesh here, 

I Added Screenshot and updated ReadMe.md
Hope that contributes to your project  

(^_^)

### CODE REVIEW

**Comment by harsh778** [comment]
Hey m8!
Thanks for your contribution!

**Comment by Neon-K9** [comment]
Glad that I could help 😊
Hoping you would like to Merge my Commit

**Comment by harsh778** [comment]
Also, in the screenshot why are the particles only contained in the name div. Instead, they should span the entire website.

**Comment by Neon-K9** [comment]
Hey,

well the error was that Animation of particles works only when that Div is on screen,
so I Screenshotted Divisions individually,

Have a look now 🙌🏻

**Comment by harsh778** [comment]
Alright!

**Comment by Neon-K9** [comment]
Hey, 
the Pull request hadn't been merged,
did you intent to close the PR?

**Comment by Neon-K9** [comment]
What do you mean by after some time? 
can you elaborate?

**Comment by harsh778** [comment]
I mean currently I am working on another project. I will restart this once I am done with my project.

**Pull request closed without merging**
